apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/robinopedro89/laboratorio-gitops.git'
    path: k8s/base/sealed-secrets
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
