apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-menu-web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/robinopedro89/laboratorio-gitops.git'
    path: apps/menu-web/overlays/dev # ¡Apunta a la nueva ruta de tu app!
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
