apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mi-secreto-db
  namespace: default
spec:
  encryptedData:
    password: AgA6qkqMfb8w218FTKhnKGV02QPX0kdRF41syMRnR8TQXjlntYLw894RLChfQNfRIONnQ6N0Z3Hx5oosFZ+JDbssuR5IBKf80QaZOM0OSqJbw/lNfFbpZi6g1LGbph/xhvPOn5mETTdPBQYDd6kJBZ017b1AoxUI5akawnkZIKdg6QqL87ErVAOJL1a9DtftJXIt7XYGrJpOwlXObyEeZP3ym0pVrpI0zu2SWh6dk6h71DvkxxMaMCoKQ2q9XiKmgShi6bU7lpsTfVv/ka4Yqgz5+rRU+HgThTBR4vJ04/2IZSO/Ywe8yr49jg2Zk+Yo5btGLiVP8Bl8aHN5rDednCj89weMYf9wAG9UGGDysiNDXDA7Fjv5NXHN7lOLH1e6AO3B6ESXAd2Y//D3rgdZjj2k9LCeXslRo1UusI5Qsx3054sWKZ1SpELhG+zUIdTEgOmreeg2yfBmzCbcIJS1zOolGOt+S+8J9Coa7lQuENxgSF6znnT6+cmacDJNRZcv9IQheddXTVlEURoJ8g/z5SmFAwUPLFIR4GjtIdcrW050vdaW48jD+JIL4QSXTl3hoMdFEtO8HEKpZmJHf2OH0BVNSALK0QAEbDfbNtQz8GBj60kLQCOQ5vk+F5k1cIGjyBcc6a7kSsbWtONiiXD1zFVA+aeMYvbEJX12a9etGhcHK2gDXpGWGw/9ANLZ6adG5RwqHL4yxqYSMMTa/tHl0Xg=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mi-secreto-db
      namespace: default
    type: Opaque

