apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: mi-secreto-db
  namespace: dev
spec:
  encryptedData:
    password: AgCWU6TTYU6ih7Lmlc0TRDqOfEoLs8oaofZ4Hci1tkvQs1G8Rd53M48ZibLooyKOWZPxsU6WDNLimI7uf7MWBE5WPvCylVNzuya10BiXgzvDbjToMFok/OkneR0PVSQ9XvKDJT81bfLewSOuZdf8uVWP2A14l6gEEaZeD73dEhmrnSvSKIejOc01BbC4EyILucg/+ATPcLpl8tWJDArYgHy4iiWv0saTA4g2f8ImDM3XhQxWj645rb8Z+/EGnTqwOAvJVr7WrVsy6mylNNlymQU3cB3kx/K9wM2lBrtuIZsbURY86W9h06dmbSeqnGWGRXjgIK1ziqWo8Y61yc7tJesEbcYc57tCDroRi4FLNAqpDg2+kMH0IJqchxKNCHYAalaoJulc6+3AUtkUy23KwooqQDfGojelDkbSo/yfysUHgLNpi+iKFe0Lb2ALf0ZIt0JqubEbMS/XP/iec9c2Cd1WjRCYD1PPMPhsAJkGOWZRc867BHe2RbjIFBIK1hT+UmAkt/sBwGAi7mCRGDFoJmSu3SnYk3Gh93Xo5cWss56rmUKx27lvxdyhRBYWF9XOfmO1ugtkkjN5q47oz5AiwaqXsgP7lvqy111lZCiXynQ3SuqeEV9V3eCYpIMyFzfobhe+f8EnLa0PsL0ZDOCarlD/zDF3fX9SPyIBUKer4+6F477QCxnz6nrnDhtuayW/X6IL9naXaDHHKbETDO21gJI=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: dev-mi-secreto-db
      namespace: dev
    type: Opaque

