apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: mi-secreto-db
  namespace: default
spec:
  encryptedData:
    password: AgCPxCEwVR6WzKSZ8b/XOeUjj7Beub8ddMLlpvA1IQ95AkKbp96MrVsBp7vk13qCPa+JkK3m4qvYLBJnalEaxd+7rmWfE8+7l9LMT7L50rbCCWQ4I0v1T41nh5n2PYuNb5xhun4dLrCqxSh5hRpXf9HChyFoEtMc6rnPJ7RARYNtqIlOOI+D8R3UEdKSO+gyI3is7NAdsczDFez2/67bn0G2EjB60rLpKrHxNv/k1xosRhqLnpRMbMCohCnRS/2VYI1ateq0RpXC+KRaqa7M2oMFi7ZaXXgXnt+ZR1ZmbCFJsC4r9n8XtZbtVVPNh5pcn6zGbva5NCh2oY+xADbwHjInQAn8tIqZA+ZiaGu/6nBQCeLjOrKqYGqo3zjdOlQJiSEILBcfYPZFYeSw5sRl/v3Ic4vlDG2XYA3lqktrvDchIrMznMS4auOfeLYANvoVTCFKIIML0AtzPD1HrUl+jjonIR5HiTI7jwDtn0ejFJYiXOTOBZk/EsLTd9c3SEigmiDJqu9LZhfP57DZua95YoBiiMDG08A4Fp124LbG/OoB8z3FLe+YLUiW1el4uO8H5A1FdykwMgZSoJ6vWmhFnIUvUBQqkd5DwOwR3D4U5lVqtJM3W8Iz4kyTBm8vuU8XSzoeBpy9umjG4DzFVIwF9yYJX6Pv3/vmLhv41i01tXNvv/8mygKOGXHpSKCeZxjRxczJ+7AXulf8dRxYqokdWvk=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: mi-secreto-db
      namespace: default
    type: Opaque

