apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: 1.16.1
    releaseName: sealed-secrets
    namespace: kube-system

# LA SOLUCION MAGICA:
# Kustomize buscará cualquier contenedor que intente usar la imagen vieja de quay.io
# y la reemplazará por la imagen pública y actualizada de Docker Hub.
images:
  - name: quay.io/bitnami/sealed-secrets-controller
    newName: docker.io/bitnami/sealed-secrets-controller
    newTag: "v0.16.0"
